disabled_rules:
    - colon
    - compiler_protocol_init
    - cyclomatic_complexity
    - file_length
    - function_body_length
    - identifier_name
    - line_length
    - opening_brace
    - optional_data_string_conversion
    - todo
    - trailing_comma
    - type_body_length
    - type_name

included:
    - "tls-inspector/"
    - "tlskit/Sources"

excluded:
    - "tls-inspector/Localization/Localization.swift"
