disabled_rules:
    - identifier_name
    - trailing_comma
    - colon
    - type_body_length
    - function_body_length
    - opening_brace
    - line_length
    - file_length
    - todo

cyclomatic_complexity: 12

included:
    - "TLS Inspector"
    - "inspect-website"
