// TLS Inspector
// Copyright (C) Ian Spence and other TLS Inspector Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import Foundation

@MainActor
public enum SupportedLanguages: String, CaseIterable, Codable {
    case English = "en"
    case Spanish = "es"
    case German = "de"
    case Dutch = "nl"
}

@MainActor
public var currentLanguage: SupportedLanguages = .English

@MainActor
public final class Localize {
    // key: 1 day
    public static func n1day() -> String {
        switch currentLanguage {
        case .English:
            return "1 day"
        case .Spanish:
            return "1 day"
        case .German:
            return "1 day"
        case .Dutch:
            return "1 day"
        }
    }
    // key: 1 hour
    public static func n1hour() -> String {
        switch currentLanguage {
        case .English:
            return "1 hour"
        case .Spanish:
            return "1 hour"
        case .German:
            return "1 hour"
        case .Dutch:
            return "1 hour"
        }
    }
    // key: 1 minute
    public static func n1minute() -> String {
        switch currentLanguage {
        case .English:
            return "1 minute"
        case .Spanish:
            return "1 minute"
        case .German:
            return "1 minute"
        case .Dutch:
            return "1 minute"
        }
    }
    // key: 1 month
    public static func n1month() -> String {
        switch currentLanguage {
        case .English:
            return "1 month"
        case .Spanish:
            return "1 month"
        case .German:
            return "1 month"
        case .Dutch:
            return "1 month"
        }
    }
    // key: 1 year
    public static func n1year() -> String {
        switch currentLanguage {
        case .English:
            return "1 year"
        case .Spanish:
            return "1 year"
        case .German:
            return "1 year"
        case .Dutch:
            return "1 year"
        }
    }
    // key: About
    public static func about() -> String {
        switch currentLanguage {
        case .English:
            return "About"
        case .Spanish:
            return "About"
        case .German:
            return "About"
        case .Dutch:
            return "About"
        }
    }
    // key: Add reminder for certificate expiry
    public static func addreminderforcertificateexpiry() -> String {
        switch currentLanguage {
        case .English:
            return "Add reminder for certificate expiry"
        case .Spanish:
            return "Add reminder for certificate expiry"
        case .German:
            return "Add reminder for certificate expiry"
        case .Dutch:
            return "Add reminder for certificate expiry"
        }
    }
    // key: Advanced Options
    public static func advancedoptions() -> String {
        switch currentLanguage {
        case .English:
            return "Advanced Options"
        case .Spanish:
            return "Advanced Options"
        case .German:
            return "Advanced Options"
        case .Dutch:
            return "Advanced Options"
        }
    }
    // key: AdvancedSettingsNag
    public static func advancedsettingsnag() -> String {
        switch currentLanguage {
        case .English:
            return "These options are for advanced investigation and troubleshooting. Using invalid values can prevent TLS Inspector from working correctly."
        case .Spanish:
            return "These options are for advanced investigation and troubleshooting. Using invalid values can prevent TLS Inspector from working correctly."
        case .German:
            return "These options are for advanced investigation and troubleshooting. Using invalid values can prevent TLS Inspector from working correctly."
        case .Dutch:
            return "These options are for advanced investigation and troubleshooting. Using invalid values can prevent TLS Inspector from working correctly."
        }
    }
    // key: Algorithm
    public static func algorithm() -> String {
        switch currentLanguage {
        case .English:
            return "Algorithm"
        case .Spanish:
            return "Algorithm"
        case .German:
            return "Algorithm"
        case .Dutch:
            return "Algorithm"
        }
    }
    // key: Allowed ciphers
    public static func allowedciphers() -> String {
        switch currentLanguage {
        case .English:
            return "Allowed ciphers"
        case .Spanish:
            return "Allowed ciphers"
        case .German:
            return "Allowed ciphers"
        case .Dutch:
            return "Allowed ciphers"
        }
    }
    // key: Alternate Names
    public static func alternatenames() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        case .Spanish:
            return "Alternate Names"
        case .German:
            return "Alternate Names"
        case .Dutch:
            return "Alternate Names"
        }
    }
    // key: App Icon
    public static func appicon() -> String {
        switch currentLanguage {
        case .English:
            return "App Icon"
        case .Spanish:
            return "App Icon"
        case .German:
            return "App Icon"
        case .Dutch:
            return "App Icon"
        }
    }
    // key: App Language
    public static func applanguage() -> String {
        switch currentLanguage {
        case .English:
            return "App Language"
        case .Spanish:
            return "App Language"
        case .German:
            return "App Language"
        case .Dutch:
            return "App Language"
        }
    }
    // key: AppIconFooter
    public static func appiconfooter() -> String {
        switch currentLanguage {
        case .English:
            return "The Progress pride flag was created by Daniel Quasar and is licensed under Creative Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .Spanish:
            return "The Progress pride flag was created by Daniel Quasar and is licensed under Creative Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .German:
            return "The Progress pride flag was created by Daniel Quasar and is licensed under Creative Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        case .Dutch:
            return "The Progress pride flag was created by Daniel Quasar and is licensed under Creative Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        }
    }
    // key: Apple
    public static func apple() -> String {
        switch currentLanguage {
        case .English:
            return "Apple"
        case .Spanish:
            return "Apple"
        case .German:
            return "Apple"
        case .Dutch:
            return "Apple"
        }
    }
    // key: Authority
    public static func authority() -> String {
        switch currentLanguage {
        case .English:
            return "Authority"
        case .Spanish:
            return "Authority"
        case .German:
            return "Authority"
        case .Dutch:
            return "Authority"
        }
    }
    // key: Auto
    public static func auto() -> String {
        switch currentLanguage {
        case .English:
            return "Auto"
        case .Spanish:
            return "Auto"
        case .German:
            return "Auto"
        case .Dutch:
            return "Auto"
        }
    }
    // key: Basic
    public static func basic() -> String {
        switch currentLanguage {
        case .English:
            return "Basic"
        case .Spanish:
            return "Basic"
        case .German:
            return "Basic"
        case .Dutch:
            return "Basic"
        }
    }
    // key: Bundle date
    public static func bundledate() -> String {
        switch currentLanguage {
        case .English:
            return "Bundle date"
        case .Spanish:
            return "Bundle date"
        case .German:
            return "Bundle date"
        case .Dutch:
            return "Bundle date"
        }
    }
    // key: Cancel
    public static func cancel() -> String {
        switch currentLanguage {
        case .English:
            return "Cancel"
        case .Spanish:
            return "Cancel"
        case .German:
            return "Cancel"
        case .Dutch:
            return "Cancel"
        }
    }
    // key: Certificate Authority
    public static func certificateauthority() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate Authority"
        case .Spanish:
            return "Certificate Authority"
        case .German:
            return "Certificate Authority"
        case .Dutch:
            return "Certificate Authority"
        }
    }
    // key: Certificate Status
    public static func certificatestatus() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate Status"
        case .Spanish:
            return "Certificate Status"
        case .German:
            return "Certificate Status"
        case .Dutch:
            return "Certificate Status"
        }
    }
    // key: Certificate Timestamps
    public static func certificatetimestamps() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate Timestamps"
        case .Spanish:
            return "Certificate Timestamps"
        case .German:
            return "Certificate Timestamps"
        case .Dutch:
            return "Certificate Timestamps"
        }
    }
    // key: Certificate Trust
    public static func certificatetrust() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate Trust"
        case .Spanish:
            return "Certificate Trust"
        case .German:
            return "Certificate Trust"
        case .Dutch:
            return "Certificate Trust"
        }
    }
    // key: Certificate not trusted
    public static func certificatenottrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate not trusted"
        case .Spanish:
            return "Certificate not trusted"
        case .German:
            return "Certificate not trusted"
        case .Dutch:
            return "Certificate not trusted"
        }
    }
    // key: CertificateStatusFooter
    public static func certificatestatusfooter() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate status checks are used to check if a certificate has been revoked."
        case .Spanish:
            return "Certificate status checks are used to check if a certificate has been revoked."
        case .German:
            return "Certificate status checks are used to check if a certificate has been revoked."
        case .Dutch:
            return "Certificate status checks are used to check if a certificate has been revoked."
        }
    }
    // key: Certificates
    public static func certificates() -> String {
        switch currentLanguage {
        case .English:
            return "Certificates"
        case .Spanish:
            return "Certificates"
        case .German:
            return "Certificates"
        case .Dutch:
            return "Certificates"
        }
    }
    // key: Check for updates
    public static func checkforupdates() -> String {
        switch currentLanguage {
        case .English:
            return "Check for updates"
        case .Spanish:
            return "Check for updates"
        case .German:
            return "Check for updates"
        case .Dutch:
            return "Check for updates"
        }
    }
    // key: City / Locality
    public static func citylocality() -> String {
        switch currentLanguage {
        case .English:
            return "City / Locality"
        case .Spanish:
            return "City / Locality"
        case .German:
            return "City / Locality"
        case .Dutch:
            return "City / Locality"
        }
    }
    // key: Clear downloaded bundles
    public static func cleardownloadedbundles() -> String {
        switch currentLanguage {
        case .English:
            return "Clear downloaded bundles"
        case .Spanish:
            return "Clear downloaded bundles"
        case .German:
            return "Clear downloaded bundles"
        case .Dutch:
            return "Clear downloaded bundles"
        }
    }
    // key: Common Name
    public static func commonname() -> String {
        switch currentLanguage {
        case .English:
            return "Common Name"
        case .Spanish:
            return "Common Name"
        case .German:
            return "Common Name"
        case .Dutch:
            return "Common Name"
        }
    }
    // key: Connection Information
    public static func connectioninformation() -> String {
        switch currentLanguage {
        case .English:
            return "Connection Information"
        case .Spanish:
            return "Connection Information"
        case .German:
            return "Connection Information"
        case .Dutch:
            return "Connection Information"
        }
    }
    // key: Contribute to TLS Inspector
    public static func contributetotlsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Contribute to TLS Inspector"
        case .Spanish:
            return "Contribute to TLS Inspector"
        case .German:
            return "Contribute to TLS Inspector"
        case .Dutch:
            return "Contribute to TLS Inspector"
        }
    }
    // key: Country
    public static func country() -> String {
        switch currentLanguage {
        case .English:
            return "Country"
        case .Spanish:
            return "Country"
        case .German:
            return "Country"
        case .Dutch:
            return "Country"
        }
    }
    // key: Critical
    public static func critical() -> String {
        switch currentLanguage {
        case .English:
            return "Critical"
        case .Spanish:
            return "Critical"
        case .German:
            return "Critical"
        case .Dutch:
            return "Critical"
        }
    }
    // key: DNS Name
    public static func dnsname() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        case .Spanish:
            return "Alternate Names"
        case .German:
            return "Alternate Names"
        case .Dutch:
            return "Alternate Names"
        }
    }
    // key: Danger
    public static func danger() -> String {
        switch currentLanguage {
        case .English:
            return "Danger"
        case .Spanish:
            return "Danger"
        case .German:
            return "Danger"
        case .Dutch:
            return "Danger"
        }
    }
    // key: Dangerous & Unsafe
    public static func dangerousunsafe() -> String {
        switch currentLanguage {
        case .English:
            return "Dangerous & Unsafe"
        case .Spanish:
            return "Dangerous & Unsafe"
        case .German:
            return "Dangerous & Unsafe"
        case .Dutch:
            return "Dangerous & Unsafe"
        }
    }
    // key: Data
    public static func data() -> String {
        switch currentLanguage {
        case .English:
            return "Data"
        case .Spanish:
            return "Data"
        case .German:
            return "Data"
        case .Dutch:
            return "Data"
        }
    }
    // key: Dismiss
    public static func dismiss() -> String {
        switch currentLanguage {
        case .English:
            return "Dismiss"
        case .Spanish:
            return "Dismiss"
        case .German:
            return "Dismiss"
        case .Dutch:
            return "Dismiss"
        }
    }
    // key: Domain Name or IP Address
    public static func domainnameoripaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Domain Name or IP Address"
        case .Spanish:
            return "Domain Name or IP Address"
        case .German:
            return "Domain Name or IP Address"
        case .Dutch:
            return "Domain Name or IP Address"
        }
    }
    // key: Done
    public static func done() -> String {
        switch currentLanguage {
        case .English:
            return "Done"
        case .Spanish:
            return "Done"
        case .German:
            return "Done"
        case .Dutch:
            return "Done"
        }
    }
    // key: Download & Check CRL
    public static func downloadcheckcrl() -> String {
        switch currentLanguage {
        case .English:
            return "Download & Check CRL"
        case .Spanish:
            return "Download & Check CRL"
        case .German:
            return "Download & Check CRL"
        case .Dutch:
            return "Download & Check CRL"
        }
    }
    // key: Downloaded
    public static func downloaded() -> String {
        switch currentLanguage {
        case .English:
            return "Downloaded"
        case .Spanish:
            return "Downloaded"
        case .German:
            return "Downloaded"
        case .Dutch:
            return "Downloaded"
        }
    }
    // key: Email Address
    public static func emailaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        case .Spanish:
            return "Alternate Names"
        case .German:
            return "Alternate Names"
        case .Dutch:
            return "Alternate Names"
        }
    }
    // key: Embedded
    public static func embedded() -> String {
        switch currentLanguage {
        case .English:
            return "Embedded"
        case .Spanish:
            return "Embedded"
        case .German:
            return "Embedded"
        case .Dutch:
            return "Embedded"
        }
    }
    // key: Engine Options
    public static func engineoptions() -> String {
        switch currentLanguage {
        case .English:
            return "Engine Options"
        case .Spanish:
            return "Engine Options"
        case .German:
            return "Engine Options"
        case .Dutch:
            return "Engine Options"
        }
    }
    // key: Error
    public static func error() -> String {
        switch currentLanguage {
        case .English:
            return "Error"
        case .Spanish:
            return "Error"
        case .German:
            return "Error"
        case .Dutch:
            return "Error"
        }
    }
    // key: Expires In
    public static func expiresin() -> String {
        switch currentLanguage {
        case .English:
            return "Expires In"
        case .Spanish:
            return "Expires In"
        case .German:
            return "Expires In"
        case .Dutch:
            return "Expires In"
        }
    }
    // key: Export certificate
    public static func exportcertificate() -> String {
        switch currentLanguage {
        case .English:
            return "Export certificate"
        case .Spanish:
            return "Export certificate"
        case .German:
            return "Export certificate"
        case .Dutch:
            return "Export certificate"
        }
    }
    // key: Export certificate chain
    public static func exportcertificatechain() -> String {
        switch currentLanguage {
        case .English:
            return "Export certificate chain"
        case .Spanish:
            return "Export certificate chain"
        case .German:
            return "Export certificate chain"
        case .Dutch:
            return "Export certificate chain"
        }
    }
    // key: Extended
    public static func extended() -> String {
        switch currentLanguage {
        case .English:
            return "Extended"
        case .Spanish:
            return "Extended"
        case .German:
            return "Extended"
        case .Dutch:
            return "Extended"
        }
    }
    // key: Extensions
    public static func extensions() -> String {
        switch currentLanguage {
        case .English:
            return "Extensions"
        case .Spanish:
            return "Extensions"
        case .German:
            return "Extensions"
        case .Dutch:
            return "Extensions"
        }
    }
    // key: Feedback Sent
    public static func feedbacksent() -> String {
        switch currentLanguage {
        case .English:
            return "Feedback Sent"
        case .Spanish:
            return "Feedback Sent"
        case .German:
            return "Feedback Sent"
        case .Dutch:
            return "Feedback Sent"
        }
    }
    // key: Fingerprints
    public static func fingerprints() -> String {
        switch currentLanguage {
        case .English:
            return "Fingerprints"
        case .Spanish:
            return "Fingerprints"
        case .German:
            return "Fingerprints"
        case .Dutch:
            return "Fingerprints"
        }
    }
    // key: Follow Us
    public static func followus() -> String {
        switch currentLanguage {
        case .English:
            return "Follow Us"
        case .Spanish:
            return "Follow Us"
        case .German:
            return "Follow Us"
        case .Dutch:
            return "Follow Us"
        }
    }
    // key: Follow us on Bluesky
    public static func followusonbluesky() -> String {
        switch currentLanguage {
        case .English:
            return "Follow us on Bluesky"
        case .Spanish:
            return "Follow us on Bluesky"
        case .German:
            return "Follow us on Bluesky"
        case .Dutch:
            return "Follow us on Bluesky"
        }
    }
    // key: Follow us on Mastodon
    public static func followusonmastodon() -> String {
        switch currentLanguage {
        case .English:
            return "Follow us on Mastodon"
        case .Spanish:
            return "Follow us on Mastodon"
        case .German:
            return "Follow us on Mastodon"
        case .Dutch:
            return "Follow us on Mastodon"
        }
    }
    // key: Found on device
    public static func foundondevice() -> String {
        switch currentLanguage {
        case .English:
            return "Found on device"
        case .Spanish:
            return "Found on device"
        case .German:
            return "Found on device"
        case .Dutch:
            return "Found on device"
        }
    }
    // key: General
    public static func general() -> String {
        switch currentLanguage {
        case .English:
            return "General"
        case .Spanish:
            return "General"
        case .German:
            return "General"
        case .Dutch:
            return "General"
        }
    }
    // key: Get Involved
    public static func getinvolved() -> String {
        switch currentLanguage {
        case .English:
            return "Get Involved"
        case .Spanish:
            return "Get Involved"
        case .German:
            return "Get Involved"
        case .Dutch:
            return "Get Involved"
        }
    }
    // key: Google
    public static func google() -> String {
        switch currentLanguage {
        case .English:
            return "Google"
        case .Spanish:
            return "Google"
        case .German:
            return "Google"
        case .Dutch:
            return "Google"
        }
    }
    // key: HTTP Headers
    public static func httpheaders() -> String {
        switch currentLanguage {
        case .English:
            return "HTTP Headers"
        case .Spanish:
            return "HTTP Headers"
        case .German:
            return "HTTP Headers"
        case .Dutch:
            return "HTTP Headers"
        }
    }
    // key: IP Address
    public static func ipaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        case .Spanish:
            return "Alternate Names"
        case .German:
            return "Alternate Names"
        case .Dutch:
            return "Alternate Names"
        }
    }
    // key: IconDark
    public static func icondark() -> String {
        switch currentLanguage {
        case .English:
            return "Dark"
        case .Spanish:
            return "Dark"
        case .German:
            return "Dark"
        case .Dutch:
            return "Dark"
        }
    }
    // key: IconDefault
    public static func icondefault() -> String {
        switch currentLanguage {
        case .English:
            return "Default"
        case .Spanish:
            return "Default"
        case .German:
            return "Default"
        case .Dutch:
            return "Default"
        }
    }
    // key: IconLight
    public static func iconlight() -> String {
        switch currentLanguage {
        case .English:
            return "Light"
        case .Spanish:
            return "Light"
        case .German:
            return "Light"
        case .Dutch:
            return "Light"
        }
    }
    // key: IconPride
    public static func iconpride() -> String {
        switch currentLanguage {
        case .English:
            return "Pride"
        case .Spanish:
            return "Pride"
        case .German:
            return "Pride"
        case .Dutch:
            return "Pride"
        }
    }
    // key: IconSkew
    public static func iconskew() -> String {
        switch currentLanguage {
        case .English:
            return "Skew"
        case .Spanish:
            return "Skew"
        case .German:
            return "Skew"
        case .Dutch:
            return "Skew"
        }
    }
    // key: IconSlate
    public static func iconslate() -> String {
        switch currentLanguage {
        case .English:
            return "Slate"
        case .Spanish:
            return "Slate"
        case .German:
            return "Slate"
        case .Dutch:
            return "Slate"
        }
    }
    // key: IconTrans
    public static func icontrans() -> String {
        switch currentLanguage {
        case .English:
            return "Trans"
        case .Spanish:
            return "Trans"
        case .German:
            return "Trans"
        case .Dutch:
            return "Trans"
        }
    }
    // key: Identifier
    public static func identifier() -> String {
        switch currentLanguage {
        case .English:
            return "Identifier"
        case .Spanish:
            return "Identifier"
        case .German:
            return "Identifier"
        case .Dutch:
            return "Identifier"
        }
    }
    // key: If you believe this to be in error, contact support from within the TLS Inspector app.
    public static func ifyoubelievethistobeinerrorcontactsupportfromwithinthetlsinspectorapp() -> String {
        switch currentLanguage {
        case .English:
            return "If you believe this to be in error, contact support from within the TLS Inspector app."
        case .Spanish:
            return "If you believe this to be in error, contact support from within the TLS Inspector app."
        case .German:
            return "If you believe this to be in error, contact support from within the TLS Inspector app."
        case .Dutch:
            return "If you believe this to be in error, contact support from within the TLS Inspector app."
        }
    }
    // key: Invalid Certificate
    public static func invalidcertificate() -> String {
        switch currentLanguage {
        case .English:
            return "Invalid Certificate"
        case .Spanish:
            return "Invalid Certificate"
        case .German:
            return "Invalid Certificate"
        case .Dutch:
            return "Invalid Certificate"
        }
    }
    // key: Is the connection to this site secure?
    public static func istheconnectiontothissitesecure() -> String {
        switch currentLanguage {
        case .English:
            return "Is the connection to this site secure?"
        case .Spanish:
            return "Is the connection to this site secure?"
        case .German:
            return "Is the connection to this site secure?"
        case .Dutch:
            return "Is the connection to this site secure?"
        }
    }
    // key: Issuer
    public static func issuer() -> String {
        switch currentLanguage {
        case .English:
            return "Issuer"
        case .Spanish:
            return "Issuer"
        case .German:
            return "Issuer"
        case .Dutch:
            return "Issuer"
        }
    }
    // key: Key Identifiers
    public static func keyidentifiers() -> String {
        switch currentLanguage {
        case .English:
            return "Key Identifiers"
        case .Spanish:
            return "Key Identifiers"
        case .German:
            return "Key Identifiers"
        case .Dutch:
            return "Key Identifiers"
        }
    }
    // key: Key Size
    public static func keysize() -> String {
        switch currentLanguage {
        case .English:
            return "Key Size"
        case .Spanish:
            return "Key Size"
        case .German:
            return "Key Size"
        case .Dutch:
            return "Key Size"
        }
    }
    // key: Key Usage
    public static func keyusage() -> String {
        switch currentLanguage {
        case .English:
            return "Key Usage"
        case .Spanish:
            return "Key Usage"
        case .German:
            return "Key Usage"
        case .Dutch:
            return "Key Usage"
        }
    }
    // key: LicenseFooter
    public static func licensefooter() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector is Free and Libre open source software (FLOSS) licensed under the GNU General Public License v3 (GPLv3). Copyright © 2016-2025 Ian Spence and other TLS Inspector contributors."
        case .Spanish:
            return "TLS Inspector is Free and Libre open source software (FLOSS) licensed under the GNU General Public License v3 (GPLv3). Copyright © 2016-2025 Ian Spence and other TLS Inspector contributors."
        case .German:
            return "TLS Inspector is Free and Libre open source software (FLOSS) licensed under the GNU General Public License v3 (GPLv3). Copyright © 2016-2025 Ian Spence and other TLS Inspector contributors."
        case .Dutch:
            return "TLS Inspector is Free and Libre open source software (FLOSS) licensed under the GNU General Public License v3 (GPLv3). Copyright © 2016-2025 Ian Spence and other TLS Inspector contributors."
        }
    }
    // key: Locally Trusted
    public static func locallytrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Locally Trusted"
        case .Spanish:
            return "Locally Trusted"
        case .German:
            return "Locally Trusted"
        case .Dutch:
            return "Locally Trusted"
        }
    }
    // key: Log ID
    public static func logid() -> String {
        switch currentLanguage {
        case .English:
            return "Log ID"
        case .Spanish:
            return "Log ID"
        case .German:
            return "Log ID"
        case .Dutch:
            return "Log ID"
        }
    }
    // key: Log Name
    public static func logname() -> String {
        switch currentLanguage {
        case .English:
            return "Log Name"
        case .Spanish:
            return "Log Name"
        case .German:
            return "Log Name"
        case .Dutch:
            return "Log Name"
        }
    }
    // key: Logging & Support
    public static func loggingsupport() -> String {
        switch currentLanguage {
        case .English:
            return "Logging & Support"
        case .Spanish:
            return "Logging & Support"
        case .German:
            return "Logging & Support"
        case .Dutch:
            return "Logging & Support"
        }
    }
    // key: LoggingFooter
    public static func loggingfooter() -> String {
        switch currentLanguage {
        case .English:
            return "If you're having a problem with TLS Inspector we may ask you to enable debug logging and submit the logs to us so we can better identify the issue. No personal information is collected, however when enabled the hosts you inspect are included. We never collect these logs unless you send them to us using the above button."
        case .Spanish:
            return "If you're having a problem with TLS Inspector we may ask you to enable debug logging and submit the logs to us so we can better identify the issue. No personal information is collected, however when enabled the hosts you inspect are included. We never collect these logs unless you send them to us using the above button."
        case .German:
            return "If you're having a problem with TLS Inspector we may ask you to enable debug logging and submit the logs to us so we can better identify the issue. No personal information is collected, however when enabled the hosts you inspect are included. We never collect these logs unless you send them to us using the above button."
        case .Dutch:
            return "If you're having a problem with TLS Inspector we may ask you to enable debug logging and submit the logs to us so we can better identify the issue. No personal information is collected, however when enabled the hosts you inspect are included. We never collect these logs unless you send them to us using the above button."
        }
    }
    // key: Mail Account Required
    public static func mailaccountrequired() -> String {
        switch currentLanguage {
        case .English:
            return "Mail Account Required"
        case .Spanish:
            return "Mail Account Required"
        case .German:
            return "Mail Account Required"
        case .Dutch:
            return "Mail Account Required"
        }
    }
    // key: Metadata
    public static func metadata() -> String {
        switch currentLanguage {
        case .English:
            return "Metadata"
        case .Spanish:
            return "Metadata"
        case .German:
            return "Metadata"
        case .Dutch:
            return "Metadata"
        }
    }
    // key: Microsoft
    public static func microsoft() -> String {
        switch currentLanguage {
        case .English:
            return "Microsoft"
        case .Spanish:
            return "Microsoft"
        case .German:
            return "Microsoft"
        case .Dutch:
            return "Microsoft"
        }
    }
    // key: More from the Developer
    public static func morefromthedeveloper() -> String {
        switch currentLanguage {
        case .English:
            return "More from the Developer"
        case .Spanish:
            return "More from the Developer"
        case .German:
            return "More from the Developer"
        case .Dutch:
            return "More from the Developer"
        }
    }
    // key: Mozilla
    public static func mozilla() -> String {
        switch currentLanguage {
        case .English:
            return "Mozilla"
        case .Spanish:
            return "Mozilla"
        case .German:
            return "Mozilla"
        case .Dutch:
            return "Mozilla"
        }
    }
    // key: Negotiated Ciphersuite
    public static func negotiatedciphersuite() -> String {
        switch currentLanguage {
        case .English:
            return "Negotiated Ciphersuite"
        case .Spanish:
            return "Negotiated Ciphersuite"
        case .German:
            return "Negotiated Ciphersuite"
        case .Dutch:
            return "Negotiated Ciphersuite"
        }
    }
    // key: Negotiated Version
    public static func negotiatedversion() -> String {
        switch currentLanguage {
        case .English:
            return "Negotiated Version"
        case .Spanish:
            return "Negotiated Version"
        case .German:
            return "Negotiated Version"
        case .Dutch:
            return "Negotiated Version"
        }
    }
    // key: Network Engine
    public static func networkengine() -> String {
        switch currentLanguage {
        case .English:
            return "Network Engine"
        case .Spanish:
            return "Network Engine"
        case .German:
            return "Network Engine"
        case .Dutch:
            return "Network Engine"
        }
    }
    // key: Network Options
    public static func networkoptions() -> String {
        switch currentLanguage {
        case .English:
            return "Network Options"
        case .Spanish:
            return "Network Options"
        case .German:
            return "Network Options"
        case .Dutch:
            return "Network Options"
        }
    }
    // key: NetworkEngineFooter
    public static func networkenginefooter() -> String {
        switch currentLanguage {
        case .English:
            return "Changing the network engine may result in TLS Inspector showing different connection information than what is used by your iOS device."
        case .Spanish:
            return "Changing the network engine may result in TLS Inspector showing different connection information than what is used by your iOS device."
        case .German:
            return "Changing the network engine may result in TLS Inspector showing different connection information than what is used by your iOS device."
        case .Dutch:
            return "Changing the network engine may result in TLS Inspector showing different connection information than what is used by your iOS device."
        }
    }
    // key: No
    public static func no() -> String {
        switch currentLanguage {
        case .English:
            return "No"
        case .Spanish:
            return "No"
        case .German:
            return "No"
        case .Dutch:
            return "No"
        }
    }
    // key: No Supported URL Found
    public static func nosupportedurlfound() -> String {
        switch currentLanguage {
        case .English:
            return "No Supported URL Found"
        case .Spanish:
            return "No Supported URL Found"
        case .German:
            return "No Supported URL Found"
        case .Dutch:
            return "No Supported URL Found"
        }
    }
    // key: Not After
    public static func notafter() -> String {
        switch currentLanguage {
        case .English:
            return "Not After"
        case .Spanish:
            return "Not After"
        case .German:
            return "Not After"
        case .Dutch:
            return "Not After"
        }
    }
    // key: Not Before
    public static func notbefore() -> String {
        switch currentLanguage {
        case .English:
            return "Not Before"
        case .Spanish:
            return "Not Before"
        case .German:
            return "Not Before"
        case .Dutch:
            return "Not Before"
        }
    }
    // key: Notice
    public static func notice() -> String {
        switch currentLanguage {
        case .English:
            return "Notice"
        case .Spanish:
            return "Notice"
        case .German:
            return "Notice"
        case .Dutch:
            return "Notice"
        }
    }
    // key: Only HTTPS URLs can be inspected.
    public static func onlyhttpsurlscanbeinspected() -> String {
        switch currentLanguage {
        case .English:
            return "Only HTTPS URLs can be inspected."
        case .Spanish:
            return "Only HTTPS URLs can be inspected."
        case .German:
            return "Only HTTPS URLs can be inspected."
        case .Dutch:
            return "Only HTTPS URLs can be inspected."
        }
    }
    // key: Open source licenses & attributions
    public static func opensourcelicensesattributions() -> String {
        switch currentLanguage {
        case .English:
            return "Open source licenses & attributions"
        case .Spanish:
            return "Open source licenses & attributions"
        case .German:
            return "Open source licenses & attributions"
        case .Dutch:
            return "Open source licenses & attributions"
        }
    }
    // key: Options
    public static func options() -> String {
        switch currentLanguage {
        case .English:
            return "Options"
        case .Spanish:
            return "Options"
        case .German:
            return "Options"
        case .Dutch:
            return "Options"
        }
    }
    // key: Organization
    public static func organization() -> String {
        switch currentLanguage {
        case .English:
            return "Organization"
        case .Spanish:
            return "Organization"
        case .German:
            return "Organization"
        case .Dutch:
            return "Organization"
        }
    }
    // key: Organizational Unit
    public static func organizationalunit() -> String {
        switch currentLanguage {
        case .English:
            return "Organizational Unit"
        case .Spanish:
            return "Organizational Unit"
        case .German:
            return "Organizational Unit"
        case .Dutch:
            return "Organizational Unit"
        }
    }
    // key: Please Note
    public static func pleasenote() -> String {
        switch currentLanguage {
        case .English:
            return "Please Note"
        case .Spanish:
            return "Please Note"
        case .German:
            return "Please Note"
        case .Dutch:
            return "Please Note"
        }
    }
    // key: Please wait...
    public static func pleasewait() -> String {
        switch currentLanguage {
        case .English:
            return "Please wait..."
        case .Spanish:
            return "Please wait..."
        case .German:
            return "Please wait..."
        case .Dutch:
            return "Please wait..."
        }
    }
    // key: ProxyDanger
    public static func proxydanger() -> String {
        switch currentLanguage {
        case .English:
            return "If you are unfamiliar with what an HTTPS proxy is or why one is configured on your device, seek assistance from Apple Support or a trusted friendly immediatly. Avoid using your device if possible."
        case .Spanish:
            return "If you are unfamiliar with what an HTTPS proxy is or why one is configured on your device, seek assistance from Apple Support or a trusted friendly immediatly. Avoid using your device if possible."
        case .German:
            return "If you are unfamiliar with what an HTTPS proxy is or why one is configured on your device, seek assistance from Apple Support or a trusted friendly immediatly. Avoid using your device if possible."
        case .Dutch:
            return "If you are unfamiliar with what an HTTPS proxy is or why one is configured on your device, seek assistance from Apple Support or a trusted friendly immediatly. Avoid using your device if possible."
        }
    }
    // key: ProxyNotice
    public static func proxynotice() -> String {
        switch currentLanguage {
        case .English:
            return "An HTTPS proxy is configured on your device. TLS Inspector is not compatible with HTTPS proxies and your inspection cannot proceed. You must disable your HTTPS proxy from your WiFi settings before you can use TLS Inspector."
        case .Spanish:
            return "An HTTPS proxy is configured on your device. TLS Inspector is not compatible with HTTPS proxies and your inspection cannot proceed. You must disable your HTTPS proxy from your WiFi settings before you can use TLS Inspector."
        case .German:
            return "An HTTPS proxy is configured on your device. TLS Inspector is not compatible with HTTPS proxies and your inspection cannot proceed. You must disable your HTTPS proxy from your WiFi settings before you can use TLS Inspector."
        case .Dutch:
            return "An HTTPS proxy is configured on your device. TLS Inspector is not compatible with HTTPS proxies and your inspection cannot proceed. You must disable your HTTPS proxy from your WiFi settings before you can use TLS Inspector."
        }
    }
    // key: Public Key
    public static func publickey() -> String {
        switch currentLanguage {
        case .English:
            return "Public Key"
        case .Spanish:
            return "Public Key"
        case .German:
            return "Public Key"
        case .Dutch:
            return "Public Key"
        }
    }
    // key: Query OCSP Responder
    public static func queryocspresponder() -> String {
        switch currentLanguage {
        case .English:
            return "Query OCSP Responder"
        case .Spanish:
            return "Query OCSP Responder"
        case .German:
            return "Query OCSP Responder"
        case .Dutch:
            return "Query OCSP Responder"
        }
    }
    // key: Quick Exit
    public static func quickexit() -> String {
        switch currentLanguage {
        case .English:
            return "Quick Exit"
        case .Spanish:
            return "Quick Exit"
        case .German:
            return "Quick Exit"
        case .Dutch:
            return "Quick Exit"
        }
    }
    // key: Rate in App Store
    public static func rateinappstore() -> String {
        switch currentLanguage {
        case .English:
            return "Rate in App Store"
        case .Spanish:
            return "Rate in App Store"
        case .German:
            return "Rate in App Store"
        case .Dutch:
            return "Rate in App Store"
        }
    }
    // key: Recent Lookups
    public static func recentlookups() -> String {
        switch currentLanguage {
        case .English:
            return "Recent Lookups"
        case .Spanish:
            return "Recent Lookups"
        case .German:
            return "Recent Lookups"
        case .Dutch:
            return "Recent Lookups"
        }
    }
    // key: Remember Recent Lookups
    public static func rememberrecentlookups() -> String {
        switch currentLanguage {
        case .English:
            return "Remember Recent Lookups"
        case .Spanish:
            return "Remember Recent Lookups"
        case .German:
            return "Remember Recent Lookups"
        case .Dutch:
            return "Remember Recent Lookups"
        }
    }
    // key: Remote Address
    public static func remoteaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Remote Address"
        case .Spanish:
            return "Remote Address"
        case .German:
            return "Remote Address"
        case .Dutch:
            return "Remote Address"
        }
    }
    // key: Reset to default settings
    public static func resettodefaultsettings() -> String {
        switch currentLanguage {
        case .English:
            return "Reset to default settings"
        case .Spanish:
            return "Reset to default settings"
        case .German:
            return "Reset to default settings"
        case .Dutch:
            return "Reset to default settings"
        }
    }
    // key: Root
    public static func root() -> String {
        switch currentLanguage {
        case .English:
            return "Root"
        case .Spanish:
            return "Root"
        case .German:
            return "Root"
        case .Dutch:
            return "Root"
        }
    }
    // key: Root CA Certificates
    public static func rootcacertificates() -> String {
        switch currentLanguage {
        case .English:
            return "Root CA Certificates"
        case .Spanish:
            return "Root CA Certificates"
        case .German:
            return "Root CA Certificates"
        case .Dutch:
            return "Root CA Certificates"
        }
    }
    // key: RootCABundleAbout
    public static func rootcabundleabout() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector uses the root CA certificates present on your device as well as from trusted vendors to yield high-confidence trust decisions. Updates to certificate bundles are infrequent and a copy is included with TLS Inspector."
        case .Spanish:
            return "TLS Inspector uses the root CA certificates present on your device as well as from trusted vendors to yield high-confidence trust decisions. Updates to certificate bundles are infrequent and a copy is included with TLS Inspector."
        case .German:
            return "TLS Inspector uses the root CA certificates present on your device as well as from trusted vendors to yield high-confidence trust decisions. Updates to certificate bundles are infrequent and a copy is included with TLS Inspector."
        case .Dutch:
            return "TLS Inspector uses the root CA certificates present on your device as well as from trusted vendors to yield high-confidence trust decisions. Updates to certificate bundles are infrequent and a copy is included with TLS Inspector."
        }
    }
    // key: RootCALicenseFooter
    public static func rootcalicensefooter() -> String {
        switch currentLanguage {
        case .English:
            return "Apple, Google, Microsoft, and Mozilla are all registered trademarks belonging to their respective owners. TLS Inspector is not affiliated with or endorsed by any third party, including but not limited to the aforementioned entities."
        case .Spanish:
            return "Apple, Google, Microsoft, and Mozilla are all registered trademarks belonging to their respective owners. TLS Inspector is not affiliated with or endorsed by any third party, including but not limited to the aforementioned entities."
        case .German:
            return "Apple, Google, Microsoft, and Mozilla are all registered trademarks belonging to their respective owners. TLS Inspector is not affiliated with or endorsed by any third party, including but not limited to the aforementioned entities."
        case .Dutch:
            return "Apple, Google, Microsoft, and Mozilla are all registered trademarks belonging to their respective owners. TLS Inspector is not affiliated with or endorsed by any third party, including but not limited to the aforementioned entities."
        }
    }
    // key: Search on Shodan
    public static func searchonshodan() -> String {
        switch currentLanguage {
        case .English:
            return "Search on Shodan"
        case .Spanish:
            return "Search on Shodan"
        case .German:
            return "Search on Shodan"
        case .Dutch:
            return "Search on Shodan"
        }
    }
    // key: Search on crt.sh
    public static func searchoncrtsh() -> String {
        switch currentLanguage {
        case .English:
            return "Search on crt.sh"
        case .Spanish:
            return "Search on crt.sh"
        case .German:
            return "Search on crt.sh"
        case .Dutch:
            return "Search on crt.sh"
        }
    }
    // key: Seconds
    public static func seconds() -> String {
        switch currentLanguage {
        case .English:
            return "Seconds"
        case .Spanish:
            return "Seconds"
        case .German:
            return "Seconds"
        case .Dutch:
            return "Seconds"
        }
    }
    // key: Security HTTP Headers
    public static func securityhttpheaders() -> String {
        switch currentLanguage {
        case .English:
            return "Security HTTP Headers"
        case .Spanish:
            return "Security HTTP Headers"
        case .German:
            return "Security HTTP Headers"
        case .Dutch:
            return "Security HTTP Headers"
        }
    }
    // key: Send Feedback
    public static func sendfeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Send Feedback"
        case .Spanish:
            return "Send Feedback"
        case .German:
            return "Send Feedback"
        case .Dutch:
            return "Send Feedback"
        }
    }
    // key: Sent by server
    public static func sentbyserver() -> String {
        switch currentLanguage {
        case .English:
            return "Sent by server"
        case .Spanish:
            return "Sent by server"
        case .German:
            return "Sent by server"
        case .Dutch:
            return "Sent by server"
        }
    }
    // key: Serial Number
    public static func serialnumber() -> String {
        switch currentLanguage {
        case .English:
            return "Serial Number"
        case .Spanish:
            return "Serial Number"
        case .German:
            return "Serial Number"
        case .Dutch:
            return "Serial Number"
        }
    }
    // key: Share & Feedback
    public static func sharefeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Share & Feedback"
        case .Spanish:
            return "Share & Feedback"
        case .German:
            return "Share & Feedback"
        case .Dutch:
            return "Share & Feedback"
        }
    }
    // key: Share TLS Inspector
    public static func sharetlsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Share TLS Inspector"
        case .Spanish:
            return "Share TLS Inspector"
        case .German:
            return "Share TLS Inspector"
        case .Dutch:
            return "Share TLS Inspector"
        }
    }
    // key: Show HTTP Headers
    public static func showhttpheaders() -> String {
        switch currentLanguage {
        case .English:
            return "Show HTTP Headers"
        case .Spanish:
            return "Show HTTP Headers"
        case .German:
            return "Show HTTP Headers"
        case .Dutch:
            return "Show HTTP Headers"
        }
    }
    // key: Show Tips
    public static func showtips() -> String {
        switch currentLanguage {
        case .English:
            return "Show Tips"
        case .Spanish:
            return "Show Tips"
        case .German:
            return "Show Tips"
        case .Dutch:
            return "Show Tips"
        }
    }
    // key: Show certificate on crt.sh
    public static func showcertificateoncrtsh() -> String {
        switch currentLanguage {
        case .English:
            return "Show certificate on crt.sh"
        case .Spanish:
            return "Show certificate on crt.sh"
        case .German:
            return "Show certificate on crt.sh"
        case .Dutch:
            return "Show certificate on crt.sh"
        }
    }
    // key: Signature
    public static func signature() -> String {
        switch currentLanguage {
        case .English:
            return "Signature"
        case .Spanish:
            return "Signature"
        case .German:
            return "Signature"
        case .Dutch:
            return "Signature"
        }
    }
    // key: Signature Type
    public static func signaturetype() -> String {
        switch currentLanguage {
        case .English:
            return "Signature Type"
        case .Spanish:
            return "Signature Type"
        case .German:
            return "Signature Type"
        case .Dutch:
            return "Signature Type"
        }
    }
    // key: Source
    public static func source() -> String {
        switch currentLanguage {
        case .English:
            return "Source"
        case .Spanish:
            return "Source"
        case .German:
            return "Source"
        case .Dutch:
            return "Source"
        }
    }
    // key: Special
    public static func special() -> String {
        switch currentLanguage {
        case .English:
            return "Special"
        case .Spanish:
            return "Special"
        case .German:
            return "Special"
        case .Dutch:
            return "Special"
        }
    }
    // key: State / Province
    public static func stateprovince() -> String {
        switch currentLanguage {
        case .English:
            return "State / Province"
        case .Spanish:
            return "State / Province"
        case .German:
            return "State / Province"
        case .Dutch:
            return "State / Province"
        }
    }
    // key: Status Providers
    public static func statusproviders() -> String {
        switch currentLanguage {
        case .English:
            return "Status Providers"
        case .Spanish:
            return "Status Providers"
        case .German:
            return "Status Providers"
        case .Dutch:
            return "Status Providers"
        }
    }
    // key: Subject
    public static func subject() -> String {
        switch currentLanguage {
        case .English:
            return "Subject"
        case .Spanish:
            return "Subject"
        case .German:
            return "Subject"
        case .Dutch:
            return "Subject"
        }
    }
    // key: Submit
    public static func submit() -> String {
        switch currentLanguage {
        case .English:
            return "Submit"
        case .Spanish:
            return "Submit"
        case .German:
            return "Submit"
        case .Dutch:
            return "Submit"
        }
    }
    // key: Submit logs
    public static func submitlogs() -> String {
        switch currentLanguage {
        case .English:
            return "Submit logs"
        case .Spanish:
            return "Submit logs"
        case .German:
            return "Submit logs"
        case .Dutch:
            return "Submit logs"
        }
    }
    // key: SupportNote
    public static func supportnote() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector does not provide you or your device with protection from viruses or malware. If you are concerned about the security of your device, contact Apple Support."
        case .Spanish:
            return "TLS Inspector does not provide you or your device with protection from viruses or malware. If you are concerned about the security of your device, contact Apple Support."
        case .German:
            return "TLS Inspector does not provide you or your device with protection from viruses or malware. If you are concerned about the security of your device, contact Apple Support."
        case .Dutch:
            return "TLS Inspector does not provide you or your device with protection from viruses or malware. If you are concerned about the security of your device, contact Apple Support."
        }
    }
    // key: TLS Inspector
    public static func tlsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector"
        case .Spanish:
            return "TLS Inspector"
        case .German:
            return "TLS Inspector"
        case .Dutch:
            return "TLS Inspector"
        }
    }
    // key: Timeout
    public static func timeout() -> String {
        switch currentLanguage {
        case .English:
            return "Timeout"
        case .Spanish:
            return "Timeout"
        case .German:
            return "Timeout"
        case .Dutch:
            return "Timeout"
        }
    }
    // key: Timestamp
    public static func timestamp() -> String {
        switch currentLanguage {
        case .English:
            return "Timestamp"
        case .Spanish:
            return "Timestamp"
        case .German:
            return "Timestamp"
        case .Dutch:
            return "Timestamp"
        }
    }
    // key: Timestamps
    public static func timestamps() -> String {
        switch currentLanguage {
        case .English:
            return "Timestamps"
        case .Spanish:
            return "Timestamps"
        case .German:
            return "Timestamps"
        case .Dutch:
            return "Timestamps"
        }
    }
    // key: Treat Unrecognized as Trusted
    public static func treatunrecognizedastrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Treat Unrecognized as Trusted"
        case .Spanish:
            return "Treat Unrecognized as Trusted"
        case .German:
            return "Treat Unrecognized as Trusted"
        case .Dutch:
            return "Treat Unrecognized as Trusted"
        }
    }
    // key: Trust Details
    public static func trustdetails() -> String {
        switch currentLanguage {
        case .English:
            return "Trust Details"
        case .Spanish:
            return "Trust Details"
        case .German:
            return "Trust Details"
        case .Dutch:
            return "Trust Details"
        }
    }
    // key: Trusted
    public static func trusted() -> String {
        switch currentLanguage {
        case .English:
            return "Trusted"
        case .Spanish:
            return "Trusted"
        case .German:
            return "Trusted"
        case .Dutch:
            return "Trusted"
        }
    }
    // key: URI
    public static func uri() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        case .Spanish:
            return "Alternate Names"
        case .German:
            return "Alternate Names"
        case .Dutch:
            return "Alternate Names"
        }
    }
    // key: Unrecognized
    public static func unrecognized() -> String {
        switch currentLanguage {
        case .English:
            return "Unrecognized"
        case .Spanish:
            return "Unrecognized"
        case .German:
            return "Unrecognized"
        case .Dutch:
            return "Unrecognized"
        }
    }
    // key: Untrusted
    public static func untrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Untrusted"
        case .Spanish:
            return "Untrusted"
        case .German:
            return "Untrusted"
        case .Dutch:
            return "Untrusted"
        }
    }
    // key: Use IP version
    public static func useipversion() -> String {
        switch currentLanguage {
        case .English:
            return "Use IP version"
        case .Spanish:
            return "Use IP version"
        case .German:
            return "Use IP version"
        case .Dutch:
            return "Use IP version"
        }
    }
    // key: Valid For
    public static func validfor() -> String {
        switch currentLanguage {
        case .English:
            return "Valid For"
        case .Spanish:
            return "Valid For"
        case .German:
            return "Valid For"
        case .Dutch:
            return "Valid For"
        }
    }
    // key: Validity Period
    public static func validityperiod() -> String {
        switch currentLanguage {
        case .English:
            return "Validity Period"
        case .Spanish:
            return "Validity Period"
        case .German:
            return "Validity Period"
        case .Dutch:
            return "Validity Period"
        }
    }
    // key: Verbose logging
    public static func verboselogging() -> String {
        switch currentLanguage {
        case .English:
            return "Verbose logging"
        case .Spanish:
            return "Verbose logging"
        case .German:
            return "Verbose logging"
        case .Dutch:
            return "Verbose logging"
        }
    }
    // key: Verified
    public static func verified() -> String {
        switch currentLanguage {
        case .English:
            return "Verified"
        case .Spanish:
            return "Verified"
        case .German:
            return "Verified"
        case .Dutch:
            return "Verified"
        }
    }
    // key: Version
    public static func version() -> String {
        switch currentLanguage {
        case .English:
            return "Version"
        case .Spanish:
            return "Version"
        case .German:
            return "Version"
        case .Dutch:
            return "Version"
        }
    }
    // key: View All
    public static func viewall() -> String {
        switch currentLanguage {
        case .English:
            return "View All"
        case .Spanish:
            return "View All"
        case .German:
            return "View All"
        case .Dutch:
            return "View All"
        }
    }
    // key: View on SSL Labs
    public static func viewonssllabs() -> String {
        switch currentLanguage {
        case .English:
            return "View on SSL Labs"
        case .Spanish:
            return "View on SSL Labs"
        case .German:
            return "View on SSL Labs"
        case .Dutch:
            return "View on SSL Labs"
        }
    }
    // key: What does this mean?
    public static func whatdoesthismean() -> String {
        switch currentLanguage {
        case .English:
            return "What does this mean?"
        case .Spanish:
            return "What does this mean?"
        case .German:
            return "What does this mean?"
        case .Dutch:
            return "What does this mean?"
        }
    }
    // key: Yes
    public static func yes() -> String {
        switch currentLanguage {
        case .English:
            return "Yes"
        case .Spanish:
            return "Yes"
        case .German:
            return "Yes"
        case .Dutch:
            return "Yes"
        }
    }
    // key: app{version}{build}{opensslversion}{curlversion}
    public static func appversionbuildopensslversioncurlversion(version: String, build: String, opensslversion: String, curlversion: String) -> String {
        switch currentLanguage {
        case .English:
            return "App: \(version) (\(build)), OpenSSL: \(opensslversion), curl: \(curlversion)"
        case .Spanish:
            return "App: \(version) (\(build)), OpenSSL: \(opensslversion), curl: \(curlversion)"
        case .German:
            return "App: \(version) (\(build)), OpenSSL: \(opensslversion), curl: \(curlversion)"
        case .Dutch:
            return "App: \(version) (\(build)), OpenSSL: \(opensslversion), curl: \(curlversion)"
        }
    }
    // key: guidance_warning
    public static func guidancewarning() -> String {
        switch currentLanguage {
        case .English:
            return "If you are seeing this warning while inspecting the website for social media, banks, personal email, then your device’s security may be compromised. Avoid using your device if you can and seek immediate assistance from Apple Support or a trusted friend."
        case .Spanish:
            return "If you are seeing this warning while inspecting the website for social media, banks, personal email, then your device’s security may be compromised. Avoid using your device if you can and seek immediate assistance from Apple Support or a trusted friend."
        case .German:
            return "If you are seeing this warning while inspecting the website for social media, banks, personal email, then your device’s security may be compromised. Avoid using your device if you can and seek immediate assistance from Apple Support or a trusted friend."
        case .Dutch:
            return "If you are seeing this warning while inspecting the website for social media, banks, personal email, then your device’s security may be compromised. Avoid using your device if you can and seek immediate assistance from Apple Support or a trusted friend."
        }
    }
    // key: whatDoesThisMean::badAuthority
    public static func whatdoesthismeanbadauthority() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate presented by the remote server was issued by a known untrustworthy & dangerous issuer or authority."
        case .Spanish:
            return "This means that the certificate presented by the remote server was issued by a known untrustworthy & dangerous issuer or authority."
        case .German:
            return "This means that the certificate presented by the remote server was issued by a known untrustworthy & dangerous issuer or authority."
        case .Dutch:
            return "This means that the certificate presented by the remote server was issued by a known untrustworthy & dangerous issuer or authority."
        }
    }
    // key: whatDoesThisMean::invalidDate
    public static func whatdoesthismeaninvaliddate() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate used by the remote host is outside of its validity period. All certificates must have a date range for when they are valid, and this certificate is currently outside of that range."
        case .Spanish:
            return "This means that the certificate used by the remote host is outside of its validity period. All certificates must have a date range for when they are valid, and this certificate is currently outside of that range."
        case .German:
            return "This means that the certificate used by the remote host is outside of its validity period. All certificates must have a date range for when they are valid, and this certificate is currently outside of that range."
        case .Dutch:
            return "This means that the certificate used by the remote host is outside of its validity period. All certificates must have a date range for when they are valid, and this certificate is currently outside of that range."
        }
    }
    // key: whatDoesThisMean::issueDateTooLong
    public static func whatdoesthismeanissuedatetoolong() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, a certificate has too long of a lifetime. All internet certificates must define a date range for which they are valid, and your device has established a maximum for that range. This certificate exceeds that maximum range."
        case .Spanish:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, a certificate has too long of a lifetime. All internet certificates must define a date range for which they are valid, and your device has established a maximum for that range. This certificate exceeds that maximum range."
        case .German:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, a certificate has too long of a lifetime. All internet certificates must define a date range for which they are valid, and your device has established a maximum for that range. This certificate exceeds that maximum range."
        case .Dutch:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, a certificate has too long of a lifetime. All internet certificates must define a date range for which they are valid, and your device has established a maximum for that range. This certificate exceeds that maximum range."
        }
    }
    // key: whatDoesThisMean::leafMissingRequiredKeyUsage
    public static func whatdoesthismeanleafmissingrequiredkeyusage() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate presented by the remote server is invalid.\n\nSpecifically, it is missing required information about what that certificate can be used for. Internet certificates can only be used for specific tasks, and this certificate is missing the required tasks in what it’s allowed to be used for."
        case .Spanish:
            return "This means that the certificate presented by the remote server is invalid.\n\nSpecifically, it is missing required information about what that certificate can be used for. Internet certificates can only be used for specific tasks, and this certificate is missing the required tasks in what it’s allowed to be used for."
        case .German:
            return "This means that the certificate presented by the remote server is invalid.\n\nSpecifically, it is missing required information about what that certificate can be used for. Internet certificates can only be used for specific tasks, and this certificate is missing the required tasks in what it’s allowed to be used for."
        case .Dutch:
            return "This means that the certificate presented by the remote server is invalid.\n\nSpecifically, it is missing required information about what that certificate can be used for. Internet certificates can only be used for specific tasks, and this certificate is missing the required tasks in what it’s allowed to be used for."
        }
    }
    // key: whatDoesThisMean::locallyTrusted
    public static func whatdoesthismeanlocallytrusted() -> String {
        switch currentLanguage {
        case .English:
            return "This means that your device has been configured to trust this connection even though it would not have done so normally.\n\nEnterprise or corporate devices may use these types of certificates for internal or private websites, but they can also be an indication of a compromised device or network."
        case .Spanish:
            return "This means that your device has been configured to trust this connection even though it would not have done so normally.\n\nEnterprise or corporate devices may use these types of certificates for internal or private websites, but they can also be an indication of a compromised device or network."
        case .German:
            return "This means that your device has been configured to trust this connection even though it would not have done so normally.\n\nEnterprise or corporate devices may use these types of certificates for internal or private websites, but they can also be an indication of a compromised device or network."
        case .Dutch:
            return "This means that your device has been configured to trust this connection even though it would not have done so normally.\n\nEnterprise or corporate devices may use these types of certificates for internal or private websites, but they can also be an indication of a compromised device or network."
        }
    }
    // key: whatDoesThisMean::revokedIntermediate
    public static func whatdoesthismeanrevokedintermediate() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        case .Spanish:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        case .German:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        case .Dutch:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        }
    }
    // key: whatDoesThisMean::revokedLeaf
    public static func whatdoesthismeanrevokedleaf() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        case .Spanish:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        case .German:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        case .Dutch:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        }
    }
    // key: whatDoesThisMean::selfSigned
    public static func whatdoesthismeanselfsigned() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificates presented by the remote host were not issued by a trusted certificate issuer or authority. Internet certificates are only trusted by your device if they were issued by responsible and reputable authorities."
        case .Spanish:
            return "This means that the certificates presented by the remote host were not issued by a trusted certificate issuer or authority. Internet certificates are only trusted by your device if they were issued by responsible and reputable authorities."
        case .German:
            return "This means that the certificates presented by the remote host were not issued by a trusted certificate issuer or authority. Internet certificates are only trusted by your device if they were issued by responsible and reputable authorities."
        case .Dutch:
            return "This means that the certificates presented by the remote host were not issued by a trusted certificate issuer or authority. Internet certificates are only trusted by your device if they were issued by responsible and reputable authorities."
        }
    }
    // key: whatDoesThisMean::sha1Intermediate
    public static func whatdoesthismeansha1intermediate() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        case .Spanish:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        case .German:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        case .Dutch:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        }
    }
    // key: whatDoesThisMean::sha1Leaf
    public static func whatdoesthismeansha1leaf() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        case .Spanish:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        case .German:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        case .Dutch:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        }
    }
    // key: whatDoesThisMean::trusted
    public static func whatdoesthismeantrusted() -> String {
        switch currentLanguage {
        case .English:
            return "This means that your device was able to establish a secure and trusted connection to the host."
        case .Spanish:
            return "This means that your device was able to establish a secure and trusted connection to the host."
        case .German:
            return "This means that your device was able to establish a secure and trusted connection to the host."
        case .Dutch:
            return "This means that your device was able to establish a secure and trusted connection to the host."
        }
    }
    // key: whatDoesThisMean::unknownCriticalExtension
    public static func whatdoesthismeanunknowncriticalextension() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, they contain information that is unknown to TLS Inspector but is marked as being critical. In this instance, the certificate cannot be trusted as TLS Inspector cannot process information that has been marked as critical."
        case .Spanish:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, they contain information that is unknown to TLS Inspector but is marked as being critical. In this instance, the certificate cannot be trusted as TLS Inspector cannot process information that has been marked as critical."
        case .German:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, they contain information that is unknown to TLS Inspector but is marked as being critical. In this instance, the certificate cannot be trusted as TLS Inspector cannot process information that has been marked as critical."
        case .Dutch:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, they contain information that is unknown to TLS Inspector but is marked as being critical. In this instance, the certificate cannot be trusted as TLS Inspector cannot process information that has been marked as critical."
        }
    }
    // key: whatDoesThisMean::untrusted
    public static func whatdoesthismeanuntrusted() -> String {
        switch currentLanguage {
        case .English:
            return "This means that your device was unable to establish a secure connection or did not have confidence in the identity of the remote host."
        case .Spanish:
            return "This means that your device was unable to establish a secure connection or did not have confidence in the identity of the remote host."
        case .German:
            return "This means that your device was unable to establish a secure connection or did not have confidence in the identity of the remote host."
        case .Dutch:
            return "This means that your device was unable to establish a secure connection or did not have confidence in the identity of the remote host."
        }
    }
    // key: whatDoesThisMean::weakRSAKey
    public static func whatdoesthismeanweakrsakey() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host are using weak cryptography. Your device needs to be able to establish a secure connection to the remote host, but the remote host has requested that your device use insecure settings for that connection."
        case .Spanish:
            return "This means that one or more certificates presented by the remote host are using weak cryptography. Your device needs to be able to establish a secure connection to the remote host, but the remote host has requested that your device use insecure settings for that connection."
        case .German:
            return "This means that one or more certificates presented by the remote host are using weak cryptography. Your device needs to be able to establish a secure connection to the remote host, but the remote host has requested that your device use insecure settings for that connection."
        case .Dutch:
            return "This means that one or more certificates presented by the remote host are using weak cryptography. Your device needs to be able to establish a secure connection to the remote host, but the remote host has requested that your device use insecure settings for that connection."
        }
    }
    // key: whatDoesThisMean::wrongHost
    public static func whatdoesthismeanwronghost() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate used by the remote host is not intended for the host you’ve connected to. Internet certificates only apply to specific domain names or IP addresses, and this certificate does not contain any values that match the host you’ve connected to."
        case .Spanish:
            return "This means that the certificate used by the remote host is not intended for the host you’ve connected to. Internet certificates only apply to specific domain names or IP addresses, and this certificate does not contain any values that match the host you’ve connected to."
        case .German:
            return "This means that the certificate used by the remote host is not intended for the host you’ve connected to. Internet certificates only apply to specific domain names or IP addresses, and this certificate does not contain any values that match the host you’ve connected to."
        case .Dutch:
            return "This means that the certificate used by the remote host is not intended for the host you’ve connected to. Internet certificates only apply to specific domain names or IP addresses, and this certificate does not contain any values that match the host you’ve connected to."
        }
    }
    // key: {number} days
    public static func numberdays(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) days"
        case .Spanish:
            return "\(number) days"
        case .German:
            return "\(number) days"
        case .Dutch:
            return "\(number) days"
        }
    }
    // key: {number} hours
    public static func numberhours(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) hours"
        case .Spanish:
            return "\(number) hours"
        case .German:
            return "\(number) hours"
        case .Dutch:
            return "\(number) hours"
        }
    }
    // key: {number} minutes
    public static func numberminutes(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) minutes"
        case .Spanish:
            return "\(number) minutes"
        case .German:
            return "\(number) minutes"
        case .Dutch:
            return "\(number) minutes"
        }
    }
    // key: {number} months
    public static func numbermonths(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) months"
        case .Spanish:
            return "\(number) months"
        case .German:
            return "\(number) months"
        case .Dutch:
            return "\(number) months"
        }
    }
    // key: {number} years
    public static func numberyears(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) years"
        case .Spanish:
            return "\(number) years"
        case .German:
            return "\(number) years"
        case .Dutch:
            return "\(number) years"
        }
    }
}
