import yaml
import re

languages = ["en"]
languageNameMap = {
    "en": "English",
}

with open('strings.yml', 'r') as file:
    dictionary = yaml.safe_load(file)

def normalizeKey(key):
    normalizedKey = re.sub(r"[^A-Za-z0-9]", "", key.lower())
    if key[0] >= '0' and key[0] <= '9':
        normalizedKey = "n" + key
    
    return normalizedKey.replace(' ', '')

def getArgs(key):
    return re.findall(r"\{[A-Za-z0-9]+\}", key)

def functionDef(key):
    args = getArgs(key)
    if args is not None:
        argsStr = []
        for arg in args:
            argsStr.append(arg[1:-1].lower() + ": String")
        return "static func " + normalizeKey(key) + "(" + ", ".join(argsStr) + ") -> String"
    else:
        return "static func " + normalizeKey(key) + "() -> String"

with open('Localization.swift', 'w') as file:
    header = """// TLS Inspector
// Copyright (C) 2025 Ian Spence
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import Foundation

@MainActor
public enum SupportedLanguages: String {
"""
    file.write(header)

    for language in languages:
        file.write("    case " + languageNameMap[language] + " = \"" + language + "\"\n")


    header = """}

@MainActor
public var currentLanguage: SupportedLanguages = .English

@MainActor
public final class Localize {
"""
    file.write(header)

    for entry in dictionary:
        file.write("    " + functionDef(entry["key"]) + " {\n")

        file.write("        switch currentLanguage {\n")

        for language in languages:
            file.write("        case ." + languageNameMap[language] + ":\n")

            args = getArgs(entry["key"])
            val = entry["values"][language]
            val = val.replace("\"", "\\\"")
            if args is not None:
                i = 0
                for arg in args:
                    val = val.replace("{" + str(i) + "}", "\\(" + arg[1:-1] + ")")
                    i = i + 1
                file.write("            return \"" + val + "\"\n")
            else:
                file.write("            return \"" + val + "\"\n")

        file.write("        }\n")
        file.write("    }\n")
    file.write("}\n")
