"""
TLS Inspector
Copyright (C) Ian Spence and other TLS Inspector Contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""
import yaml
import re
import os

languages = ["en"]
languageNameMap = {
    "en": "English",
}

with open('strings.yml', 'r') as file:
    dictionary = yaml.safe_load(file)

def normalizeKey(key):
    normalizedKey = re.sub(r"[^A-Za-z0-9]", "", key.lower())
    if key[0] >= '0' and key[0] <= '9':
        normalizedKey = "n" + key
    
    return normalizedKey.replace(' ', '')

def getArgs(key):
    return re.findall(r"\{[A-Za-z0-9]+\}", key)

def functionDef(key):
    args = getArgs(key)
    if args is not None:
        argsStr = []
        for arg in args:
            argsStr.append(arg[1:-1].lower() + ": String")
        return "static func " + normalizeKey(key) + "(" + ", ".join(argsStr) + ") -> String"
    else:
        return "static func " + normalizeKey(key) + "() -> String"

with open('Localization.swift.new', 'w') as file:
    header = """// TLS Inspector
// Copyright (C) Ian Spence and other TLS Inspector Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import Foundation

@MainActor
public enum SupportedLanguages: String {
"""
    file.write(header)

    for language in languages:
        file.write("    case " + languageNameMap[language] + " = \"" + language + "\"\n")


    header = """}

@MainActor
public var currentLanguage: SupportedLanguages = .English

@MainActor
public final class Localize {
"""
    file.write(header)

    for entry in dictionary:
        file.write("    " + functionDef(entry["key"]) + " {\n")

        file.write("        switch currentLanguage {\n")

        for language in languages:
            file.write("        case ." + languageNameMap[language] + ":\n")

            args = getArgs(entry["key"])
            val = entry["values"][language]
            val = val.replace("\"", "\\\"")
            if args is not None:
                i = 0
                for arg in args:
                    val = val.replace("{" + str(i) + "}", "\\(" + arg[1:-1] + ")")
                    i = i + 1
                file.write("            return \"" + val + "\"\n")
            else:
                file.write("            return \"" + val + "\"\n")

        file.write("        }\n")
        file.write("    }\n")
    file.write("}\n")

os.rename('Localization.swift.new', 'Localization.swift')

# Sort strings file
with open('strings.yml', 'r') as reader:
    with open('strings-sorted.yml', 'w') as writer:
        # First lines of the file are copyright and license

        in_header = True

        in_string_entry = False
        entry_buffer = ""
        entry_key = ""
        string_entries = {}

        line_num = 0

        for line in reader:
            line_num += 1

            if line_num <= 3:
                writer.write(line)
                continue

            if line[0] == "#":
                if entry_key != "":
                    string_entries[entry_key] = entry_buffer
                    entry_key = ""
                    entry_buffer = ""

                entry_buffer += line
            elif line[0] == "-":
                if entry_key != "":
                    string_entries[entry_key] = entry_buffer
                    entry_key = ""
                    entry_buffer = ""

                entry_key = line.replace("- key: ", "").replace("\"", "").lower().rstrip()
                entry_buffer += line
            else:
                entry_buffer += line

        sorted_keys = sorted(string_entries.keys())

        for key in sorted_keys:
            writer.write(string_entries[key])

os.rename('strings-sorted.yml', 'strings.yml')
