// TLS Inspector
// Copyright (C) Ian Spence and other TLS Inspector Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import Foundation

@MainActor
public enum SupportedLanguages: String {
    case English = "en"
}

@MainActor
public var currentLanguage: SupportedLanguages = .English

@MainActor
public final class Localize {
    static func about() -> String {
        switch currentLanguage {
        case .English:
            return "About"
        }
    }
    static func trusted() -> String {
        switch currentLanguage {
        case .English:
            return "Trusted"
        }
    }
    static func locallytrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Locally Trusted"
        }
    }
    static func untrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Untrusted"
        }
    }
    static func unrecognized() -> String {
        switch currentLanguage {
        case .English:
            return "Unrecognized"
        }
    }
    static func dangerousunsafe() -> String {
        switch currentLanguage {
        case .English:
            return "Dangerous & Unsafe"
        }
    }
    static func trustdetails() -> String {
        switch currentLanguage {
        case .English:
            return "Trust Details"
        }
    }
    static func whatdoesthismean() -> String {
        switch currentLanguage {
        case .English:
            return "What does this mean?"
        }
    }
    static func whatdoesthismeantrusted() -> String {
        switch currentLanguage {
        case .English:
            return "This means that your device was able to establish a secure and trusted connection to the host."
        }
    }
    static func whatdoesthismeanlocallytrusted() -> String {
        switch currentLanguage {
        case .English:
            return "This means that your device has been configured to trust this connection even though it would not have done so normally.\n\nEnterprise or corporate devices may use these types of certificates for internal or private websites, but they can also be an indication of a compromised device or network."
        }
    }
    static func whatdoesthismeanuntrusted() -> String {
        switch currentLanguage {
        case .English:
            return "This means that your device was unable to establish a secure connection or did not have confidence in the identity of the remote host."
        }
    }
    static func whatdoesthismeaninvaliddate() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate used by the remote host is outside of its validity period. All certificates must have a date range for when they are valid, and this certificate is currently outside of that range."
        }
    }
    static func whatdoesthismeanwronghost() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate used by the remote host is not intended for the host you’ve connected to. Internet certificates only apply to specific domain names or IP addresses, and this certificate does not contain any values that match the host you’ve connected to."
        }
    }
    static func whatdoesthismeansha1leaf() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        }
    }
    static func whatdoesthismeansha1intermediate() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host uses the SHA-1 algorithm. This algorithm was widely used but has been found to be vulnerable and is no longer considered secure."
        }
    }
    static func whatdoesthismeanselfsigned() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificates presented by the remote host were not issued by a trusted certificate issuer or authority. Internet certificates are only trusted by your device if they were issued by responsible and reputable authorities."
        }
    }
    static func whatdoesthismeanrevokedleaf() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        }
    }
    static func whatdoesthismeanrevokedintermediate() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host have been marked as “revoked”. Certificates are revoked when they can no longer be trusted due to several reasons."
        }
    }
    static func whatdoesthismeanweakrsakey() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote host are using weak cryptography. Your device needs to be able to establish a secure connection to the remote host, but the remote host has requested that your device use insecure settings for that connection."
        }
    }
    static func whatdoesthismeanissuedatetoolong() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, a certificate has too long of a lifetime. All internet certificates must define a date range for which they are valid, and your device has established a maximum for that range. This certificate exceeds that maximum range."
        }
    }
    static func whatdoesthismeanleafmissingrequiredkeyusage() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate presented by the remote server is invalid.\n\nSpecifically, it is missing required information about what that certificate can be used for. Internet certificates can only be used for specific tasks, and this certificate is missing the required tasks in what it’s allowed to be used for."
        }
    }
    static func whatdoesthismeanunknowncriticalextension() -> String {
        switch currentLanguage {
        case .English:
            return "This means that one or more certificates presented by the remote server are invalid.\n\nSpecifically, they contain information that is unknown to TLS Inspector but is marked as being critical. In this instance, the certificate cannot be trusted as TLS Inspector cannot process information that has been marked as critical."
        }
    }
    static func whatdoesthismeanbadauthority() -> String {
        switch currentLanguage {
        case .English:
            return "This means that the certificate presented by the remote server was issued by a known untrustworthy & dangerous issuer or authority."
        }
    }
    static func istheconnectiontothissitesecure() -> String {
        switch currentLanguage {
        case .English:
            return "Is the connection to this site secure?"
        }
    }
    static func danger() -> String {
        switch currentLanguage {
        case .English:
            return "Danger"
        }
    }
    static func invalidcertificate() -> String {
        switch currentLanguage {
        case .English:
            return "Invalid Certificate"
        }
    }
    static func guidancewarning() -> String {
        switch currentLanguage {
        case .English:
            return "If you are seeing this warning while inspecting the website for social media, banks, personal email, then your device’s security may be compromised. Avoid using your device if you can and seek immediate assistance from Apple Support or a trusted friend."
        }
    }
    static func quickexit() -> String {
        switch currentLanguage {
        case .English:
            return "Quick Exit"
        }
    }
    static func dnsname() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        }
    }
    static func emailaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        }
    }
    static func ipaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        }
    }
    static func uri() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        }
    }
    static func alternatenames() -> String {
        switch currentLanguage {
        case .English:
            return "Alternate Names"
        }
    }
    static func fingerprints() -> String {
        switch currentLanguage {
        case .English:
            return "Fingerprints"
        }
    }
    static func issuer() -> String {
        switch currentLanguage {
        case .English:
            return "Issuer"
        }
    }
    static func commonname() -> String {
        switch currentLanguage {
        case .English:
            return "Common Name"
        }
    }
    static func country() -> String {
        switch currentLanguage {
        case .English:
            return "Country"
        }
    }
    static func citylocality() -> String {
        switch currentLanguage {
        case .English:
            return "City / Locality"
        }
    }
    static func stateprovince() -> String {
        switch currentLanguage {
        case .English:
            return "State / Province"
        }
    }
    static func organization() -> String {
        switch currentLanguage {
        case .English:
            return "Organization"
        }
    }
    static func organizationalunit() -> String {
        switch currentLanguage {
        case .English:
            return "Organizational Unit"
        }
    }
    static func keyidentifiers() -> String {
        switch currentLanguage {
        case .English:
            return "Key Identifiers"
        }
    }
    static func subject() -> String {
        switch currentLanguage {
        case .English:
            return "Subject"
        }
    }
    static func authority() -> String {
        switch currentLanguage {
        case .English:
            return "Authority"
        }
    }
    static func keyusage() -> String {
        switch currentLanguage {
        case .English:
            return "Key Usage"
        }
    }
    static func basic() -> String {
        switch currentLanguage {
        case .English:
            return "Basic"
        }
    }
    static func extended() -> String {
        switch currentLanguage {
        case .English:
            return "Extended"
        }
    }
    static func metadata() -> String {
        switch currentLanguage {
        case .English:
            return "Metadata"
        }
    }
    static func serialnumber() -> String {
        switch currentLanguage {
        case .English:
            return "Serial Number"
        }
    }
    static func certificateauthority() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate Authority"
        }
    }
    static func yes() -> String {
        switch currentLanguage {
        case .English:
            return "Yes"
        }
    }
    static func no() -> String {
        switch currentLanguage {
        case .English:
            return "No"
        }
    }
    static func version() -> String {
        switch currentLanguage {
        case .English:
            return "Version"
        }
    }
    static func certificatetimestamps() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate Timestamps"
        }
    }
    static func publickey() -> String {
        switch currentLanguage {
        case .English:
            return "Public Key"
        }
    }
    static func algorithm() -> String {
        switch currentLanguage {
        case .English:
            return "Algorithm"
        }
    }
    static func signature() -> String {
        switch currentLanguage {
        case .English:
            return "Signature"
        }
    }
    static func keysize() -> String {
        switch currentLanguage {
        case .English:
            return "Key Size"
        }
    }
    static func statusproviders() -> String {
        switch currentLanguage {
        case .English:
            return "Status Providers"
        }
    }
    static func logid() -> String {
        switch currentLanguage {
        case .English:
            return "Log ID"
        }
    }
    static func logname() -> String {
        switch currentLanguage {
        case .English:
            return "Log Name"
        }
    }
    static func timestamp() -> String {
        switch currentLanguage {
        case .English:
            return "Timestamp"
        }
    }
    static func signaturetype() -> String {
        switch currentLanguage {
        case .English:
            return "Signature Type"
        }
    }
    static func timestamps() -> String {
        switch currentLanguage {
        case .English:
            return "Timestamps"
        }
    }
    static func validityperiod() -> String {
        switch currentLanguage {
        case .English:
            return "Validity Period"
        }
    }
    static func notbefore() -> String {
        switch currentLanguage {
        case .English:
            return "Not Before"
        }
    }
    static func notafter() -> String {
        switch currentLanguage {
        case .English:
            return "Not After"
        }
    }
    static func validfor() -> String {
        switch currentLanguage {
        case .English:
            return "Valid For"
        }
    }
    static func expiresin() -> String {
        switch currentLanguage {
        case .English:
            return "Expires In"
        }
    }
    static func n1year() -> String {
        switch currentLanguage {
        case .English:
            return "1 year"
        }
    }
    static func n1month() -> String {
        switch currentLanguage {
        case .English:
            return "1 month"
        }
    }
    static func n1day() -> String {
        switch currentLanguage {
        case .English:
            return "1 day"
        }
    }
    static func n1hour() -> String {
        switch currentLanguage {
        case .English:
            return "1 hour"
        }
    }
    static func n1minute() -> String {
        switch currentLanguage {
        case .English:
            return "1 minute"
        }
    }
    static func numberyears(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) years"
        }
    }
    static func numbermonths(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) months"
        }
    }
    static func numberdays(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) days"
        }
    }
    static func numberhours(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) hours"
        }
    }
    static func numberminutes(number: String) -> String {
        switch currentLanguage {
        case .English:
            return "\(number) minutes"
        }
    }
    static func httpheaders() -> String {
        switch currentLanguage {
        case .English:
            return "HTTP Headers"
        }
    }
    static func certificates() -> String {
        switch currentLanguage {
        case .English:
            return "Certificates"
        }
    }
    static func root() -> String {
        switch currentLanguage {
        case .English:
            return "Root"
        }
    }
    static func connectioninformation() -> String {
        switch currentLanguage {
        case .English:
            return "Connection Information"
        }
    }
    static func negotiatedciphersuite() -> String {
        switch currentLanguage {
        case .English:
            return "Negotiated Ciphersuite"
        }
    }
    static func negotiatedversion() -> String {
        switch currentLanguage {
        case .English:
            return "Negotiated Version"
        }
    }
    static func remoteaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Remote Address"
        }
    }
    static func securityhttpheaders() -> String {
        switch currentLanguage {
        case .English:
            return "Security HTTP Headers"
        }
    }
    static func viewall() -> String {
        switch currentLanguage {
        case .English:
            return "View All"
        }
    }
    static func domainnameoripaddress() -> String {
        switch currentLanguage {
        case .English:
            return "Domain Name or IP Address"
        }
    }
    static func pleasewait() -> String {
        switch currentLanguage {
        case .English:
            return "Please wait..."
        }
    }
    static func dismiss() -> String {
        switch currentLanguage {
        case .English:
            return "Dismiss"
        }
    }
    static func error() -> String {
        switch currentLanguage {
        case .English:
            return "Error"
        }
    }
    static func options() -> String {
        switch currentLanguage {
        case .English:
            return "Options"
        }
    }
    static func general() -> String {
        switch currentLanguage {
        case .English:
            return "General"
        }
    }
    static func special() -> String {
        switch currentLanguage {
        case .English:
            return "Special"
        }
    }
    static func rememberrecentlookups() -> String {
        switch currentLanguage {
        case .English:
            return "Remember Recent Lookups"
        }
    }
    static func showhttpheaders() -> String {
        switch currentLanguage {
        case .English:
            return "Show HTTP Headers"
        }
    }
    static func showtips() -> String {
        switch currentLanguage {
        case .English:
            return "Show Tips"
        }
    }
    static func treatunrecognizedastrusted() -> String {
        switch currentLanguage {
        case .English:
            return "Treat Unrecognized as Trusted"
        }
    }
    static func appicon() -> String {
        switch currentLanguage {
        case .English:
            return "App Icon"
        }
    }
    static func applanguage() -> String {
        switch currentLanguage {
        case .English:
            return "App Language"
        }
    }
    static func certificatestatus() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate Status"
        }
    }
    static func queryocspresponder() -> String {
        switch currentLanguage {
        case .English:
            return "Query OCSP Responder"
        }
    }
    static func downloadcheckcrl() -> String {
        switch currentLanguage {
        case .English:
            return "Download & Check CRL"
        }
    }
    static func advancedoptions() -> String {
        switch currentLanguage {
        case .English:
            return "Advanced Options"
        }
    }
    static func certificatestatusfooter() -> String {
        switch currentLanguage {
        case .English:
            return "Certificate status checks are used to check if a certificate has been revoked."
        }
    }
    static func advancedsettingsnag() -> String {
        switch currentLanguage {
        case .English:
            return "These options are for advanced investigation and troubleshooting. Using invalid values can prevent TLS Inspector from working correctly."
        }
    }
    static func networkengine() -> String {
        switch currentLanguage {
        case .English:
            return "Network Engine"
        }
    }
    static func networkenginefooter() -> String {
        switch currentLanguage {
        case .English:
            return "Changing the network engine may result in TLS Inspector showing different connection information than what is used by your iOS device."
        }
    }
    static func networkoptions() -> String {
        switch currentLanguage {
        case .English:
            return "Network Options"
        }
    }
    static func useipversion() -> String {
        switch currentLanguage {
        case .English:
            return "Use IP version"
        }
    }
    static func timeout() -> String {
        switch currentLanguage {
        case .English:
            return "Timeout"
        }
    }
    static func auto() -> String {
        switch currentLanguage {
        case .English:
            return "Auto"
        }
    }
    static func allowedciphers() -> String {
        switch currentLanguage {
        case .English:
            return "Allowed ciphers"
        }
    }
    static func seconds() -> String {
        switch currentLanguage {
        case .English:
            return "Seconds"
        }
    }
    static func engineoptions() -> String {
        switch currentLanguage {
        case .English:
            return "Engine Options"
        }
    }
    static func verboselogging() -> String {
        switch currentLanguage {
        case .English:
            return "Verbose logging"
        }
    }
    static func submitlogs() -> String {
        switch currentLanguage {
        case .English:
            return "Submit logs"
        }
    }
    static func loggingfooter() -> String {
        switch currentLanguage {
        case .English:
            return "If you're having a problem with TLS Inspector we may ask you to enable debug logging and submit the logs to us so we can better identify the issue. No personal information is collected, however when enabled the hosts you inspect are included. We never collect these logs unless you send them to us using the above button."
        }
    }
    static func loggingsupport() -> String {
        switch currentLanguage {
        case .English:
            return "Logging & Support"
        }
    }
    static func rootcacertificates() -> String {
        switch currentLanguage {
        case .English:
            return "Root CA Certificates"
        }
    }
    static func resettodefaultsettings() -> String {
        switch currentLanguage {
        case .English:
            return "Reset to default settings"
        }
    }
    static func done() -> String {
        switch currentLanguage {
        case .English:
            return "Done"
        }
    }
    static func bundledate() -> String {
        switch currentLanguage {
        case .English:
            return "Bundle date"
        }
    }
    static func embedded() -> String {
        switch currentLanguage {
        case .English:
            return "Embedded"
        }
    }
    static func verified() -> String {
        switch currentLanguage {
        case .English:
            return "Verified"
        }
    }
    static func checkforupdates() -> String {
        switch currentLanguage {
        case .English:
            return "Check for updates"
        }
    }
    static func icondefault() -> String {
        switch currentLanguage {
        case .English:
            return "Default"
        }
    }
    static func iconlight() -> String {
        switch currentLanguage {
        case .English:
            return "Light"
        }
    }
    static func icondark() -> String {
        switch currentLanguage {
        case .English:
            return "Dark"
        }
    }
    static func iconskew() -> String {
        switch currentLanguage {
        case .English:
            return "Skew"
        }
    }
    static func iconslate() -> String {
        switch currentLanguage {
        case .English:
            return "Slate"
        }
    }
    static func iconpride() -> String {
        switch currentLanguage {
        case .English:
            return "Pride"
        }
    }
    static func icontrans() -> String {
        switch currentLanguage {
        case .English:
            return "Trans"
        }
    }
    static func appiconfooter() -> String {
        switch currentLanguage {
        case .English:
            return "The \"Progress\" pride flag was created by Daniel Quasar and is licensed under Creative Commons BY-NC-SA. The trans flag was created by Monica Helms and was released to the public domain."
        }
    }
    static func rootcabundleabout() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector uses the root CA certificates present on your device as well as from trusted vendors to yield high-confidence trust decisions. Updates to certificate bundles are infrequent and a copy is included with TLS Inspector."
        }
    }
    static func source() -> String {
        switch currentLanguage {
        case .English:
            return "Source"
        }
    }
    static func downloaded() -> String {
        switch currentLanguage {
        case .English:
            return "Downloaded"
        }
    }
    static func recentlookups() -> String {
        switch currentLanguage {
        case .English:
            return "Recent Lookups"
        }
    }
    static func extensions() -> String {
        switch currentLanguage {
        case .English:
            return "Extensions"
        }
    }
    static func identifier() -> String {
        switch currentLanguage {
        case .English:
            return "Identifier"
        }
    }
    static func critical() -> String {
        switch currentLanguage {
        case .English:
            return "Critical"
        }
    }
    static func data() -> String {
        switch currentLanguage {
        case .English:
            return "Data"
        }
    }
    static func notice() -> String {
        switch currentLanguage {
        case .English:
            return "Notice"
        }
    }
    static func proxynotice() -> String {
        switch currentLanguage {
        case .English:
            return "An HTTPS proxy is configured on your device. TLS Inspector is not compatible with HTTPS proxies and your inspection cannot proceed. You must disable your HTTPS proxy from your WiFi settings before you can use TLS Inspector."
        }
    }
    static func proxydanger() -> String {
        switch currentLanguage {
        case .English:
            return "If you are unfamiliar with what an HTTPS proxy is or why one is configured on your device, seek assistance from Apple Support or a trusted friendly immediatly. Avoid using your device if possible."
        }
    }
    static func sentbyserver() -> String {
        switch currentLanguage {
        case .English:
            return "Sent by server"
        }
    }
    static func foundondevice() -> String {
        switch currentLanguage {
        case .English:
            return "Found on device"
        }
    }
    static func addreminderforcertificateexpiry() -> String {
        switch currentLanguage {
        case .English:
            return "Add reminder for certificate expiry"
        }
    }
    static func exportcertificate() -> String {
        switch currentLanguage {
        case .English:
            return "Export certificate"
        }
    }
    static func exportcertificatechain() -> String {
        switch currentLanguage {
        case .English:
            return "Export certificate chain"
        }
    }
    static func searchoncrtsh() -> String {
        switch currentLanguage {
        case .English:
            return "Search on crt.sh"
        }
    }
    static func searchonshodan() -> String {
        switch currentLanguage {
        case .English:
            return "Search on Shodan"
        }
    }
    static func showcertificateoncrtsh() -> String {
        switch currentLanguage {
        case .English:
            return "Show certificate on crt.sh"
        }
    }
    static func viewonssllabs() -> String {
        switch currentLanguage {
        case .English:
            return "View on SSL Labs"
        }
    }
    static func sharetlsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Share TLS Inspector"
        }
    }
    static func rateinappstore() -> String {
        switch currentLanguage {
        case .English:
            return "Rate in App Store"
        }
    }
    static func sharefeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Share & Feedback"
        }
    }
    static func appversionbuildopensslversioncurlversion(version: String, build: String, opensslversion: String, curlversion: String) -> String {
        switch currentLanguage {
        case .English:
            return "App: \(version) (\(build)), OpenSSL: \(opensslversion), curl: \(curlversion)"
        }
    }
    static func followus() -> String {
        switch currentLanguage {
        case .English:
            return "Follow Us"
        }
    }
    static func getinvolved() -> String {
        switch currentLanguage {
        case .English:
            return "Get Involved"
        }
    }
    static func morefromthedeveloper() -> String {
        switch currentLanguage {
        case .English:
            return "More from the Developer"
        }
    }
    static func followusonmastodon() -> String {
        switch currentLanguage {
        case .English:
            return "Follow us on Mastodon"
        }
    }
    static func followusonbluesky() -> String {
        switch currentLanguage {
        case .English:
            return "Follow us on Bluesky"
        }
    }
    static func contributetotlsinspector() -> String {
        switch currentLanguage {
        case .English:
            return "Contribute to TLS Inspector"
        }
    }
    static func providefeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Provide Feedback"
        }
    }
    static func opensourcelicensesattributions() -> String {
        switch currentLanguage {
        case .English:
            return "Open source licenses & attributions"
        }
    }
    static func licensefooter() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector is Free and Libre open source software (FLOSS) licensed under the GNU General Public License v3 (GPLv3). Copyright © 2016-2025 Ian Spence and other TLS Inspector contributors."
        }
    }
    static func rootcalicensefooter() -> String {
        switch currentLanguage {
        case .English:
            return "Apple, Google, Microsoft, and Mozilla are all registered trademarks belonging to their respective owners. TLS Inspector is not affiliated with or endorsed by any third party, including but not limited to the aforementioned entities."
        }
    }
    static func cancel() -> String {
        switch currentLanguage {
        case .English:
            return "Cancel"
        }
    }
    static func contactsupportrequiresmailaccount() -> String {
        switch currentLanguage {
        case .English:
            return "Contacting support requires that at least one email account be configured on this device."
        }
    }
    static func feedbacksent() -> String {
        switch currentLanguage {
        case .English:
            return "Feedback Sent"
        }
    }
    static func mailaccountrequired() -> String {
        switch currentLanguage {
        case .English:
            return "Mail Account Required"
        }
    }
    static func pleasenote() -> String {
        switch currentLanguage {
        case .English:
            return "Please Note"
        }
    }
    static func providedetails() -> String {
        switch currentLanguage {
        case .English:
            return "Provide Details"
        }
    }
    static func providefeedbackdetails() -> String {
        switch currentLanguage {
        case .English:
            return "Provide Feedback Details"
        }
    }
    static func reportabug() -> String {
        switch currentLanguage {
        case .English:
            return "Report a Bug"
        }
    }
    static func requestafeature() -> String {
        switch currentLanguage {
        case .English:
            return "Request a Feature"
        }
    }
    static func selectfeedbacktype() -> String {
        switch currentLanguage {
        case .English:
            return "Select Feedback Type"
        }
    }
    static func sendfeedback() -> String {
        switch currentLanguage {
        case .English:
            return "Send Feedback"
        }
    }
    static func somethingelse() -> String {
        switch currentLanguage {
        case .English:
            return "Something Else"
        }
    }
    static func submit() -> String {
        switch currentLanguage {
        case .English:
            return "Submit"
        }
    }
    static func supportisonlyprovidedinenglish() -> String {
        switch currentLanguage {
        case .English:
            return "Support is only provided in English."
        }
    }
    static func supportnote() -> String {
        switch currentLanguage {
        case .English:
            return "TLS Inspector does not provide you or your device with protection from viruses or malware. If you are concerned about the security of your device, contact Apple Support."
        }
    }
    static func yourfeedbackhasbeensent() -> String {
        switch currentLanguage {
        case .English:
            return "Your feedback has been sent."
        }
    }
}
