// TLS Inspector
// Copyright (C) Ian Spence and other TLS Inspector Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import SwiftUI

internal extension Color {
    static let accentColor = Color("AccentColor", bundle: .module)
    static let trustColourLocallyTrusted = Color("TrustColourLocallyTrusted", bundle: .module)
    static let trustColourUntrusted = Color("TrustColourUntrusted", bundle: .module)
    static let trustColourError = Color("TrustColourError", bundle: .module)
    static let trustColourTrusted = Color("TrustColourTrusted", bundle: .module)
    static let trustColourDanger = Color("TrustColourDanger", bundle: .module)
}

internal extension ShapeStyle where Self == Color {
    static var accentColor: Color { Color.accentColor }
    static var trustColourLocallyTrusted: Color { Color.trustColourLocallyTrusted }
    static var trustColourUntrusted: Color { Color.trustColourUntrusted }
    static var trustColourError: Color { Color.trustColourError }
    static var trustColourTrusted: Color { Color.trustColourTrusted }
    static var trustColourDanger: Color { Color.trustColourDanger }
}
