disabled_rules:
    - identifier_name
    - trailing_comma
    - colon
    - type_body_length
    - function_body_length
excluded:
    - 'AppDelegate.swift'
    - 'SceneDelegate.swift'
    - 'External/'
