"""
TLS Inspector
Copyright (C) Ian Spence and other TLS Inspector Contributors

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <https://www.gnu.org/licenses/>.
"""

import os
from pathlib import Path

colorsets = list(Path('../Sources/TLSUI/Resources/TLSUI.xcassets').rglob("*.colorset"))

def generate_colors():
    color_path = '../Sources/TLSUI/Extensions/Color.swift'

    with open(color_path+'.new', 'w') as file:
        colors = []
        for colorset in colorsets:
            parts = str(colorset).split('/')
            name = parts[len(parts)-1].replace('.colorset', '')
            key = name[0].lower() + name[1:]
            colors.append({
                "name": name,
                "key": key
            })

        file.write("""// TLS Inspector
// Copyright (C) Ian Spence and other TLS Inspector Contributors
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

// DO NOT EDIT THIS FILE DIRECTLY!
// This file is generated automatically using the lang.py script located in
// the same directory as this file

import SwiftUI

internal extension Color {
""")

        for color in colors:
            file.write("    static let " + color["key"] + " = Color(\"" + color["name"] + "\", bundle: .module)\n")

        file.write("}\n")

        file.write("\ninternal extension ShapeStyle where Self == Color {\n")

        for color in colors:
            file.write("    static var " + color["key"] + ": Color { Color." + color["key"] + " }\n")

        file.write("}\n")

    os.rename(color_path+'.new', color_path)

generate_colors()
