name: "Build App"

on:
  push:
    paths:
      - '.github/workflows/build_app.yml'
      - 'tls-inspector.xcodeproj/**'
      - 'tls-inspector/**'
      - 'inspect-website/**'
      - 'tlsui/**'
      - 'tlskit/**'
      - '.swiftlint.yml'
  pull_request:
    paths:
      - '.github/workflows/build_app.yml'
      - 'tls-inspector.xcodeproj/**'
      - 'tls-inspector/**'
      - 'inspect-website/**'
      - 'tlsui/**'
      - 'tlskit/**'
      - '.swiftlint.yml'

permissions:
  packages: read

env:
  TEST_DEVICE: "iPhone 17 Pro"
  XCODE_VERSION: "Xcode_26.3" # https://github.com/actions/runner-images/blob/main/images/macos/macos-26-arm64-Readme.md

jobs:
  build:
    name: "Build App"
    runs-on: macos-26
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #pin v6.0.2
        with:
          persist-credentials: false

      - name: Install Profile and Certificates
        id: install_credentials
        run: |
          echo '${{ secrets.TLS_INSPECTOR_DEVELOPMENT_PROVISIONING_PROFILE }}' > TLS_Inspector.mobileprovision.base64
          echo '${{ secrets.INSPECT_CERTIFICATE_DEVELOPMENT_PROVISIONING_PROFILE }}' > Inspect_Website.mobileprovision.base64
          base64 -i TLS_Inspector.mobileprovision.base64 -o TLS_Inspector.mobileprovision --decode && rm TLS_Inspector.mobileprovision.base64
          base64 -i Inspect_Website.mobileprovision.base64 -o Inspect_Website.mobileprovision --decode && rm Inspect_Website.mobileprovision.base64
          mkdir -p "~/Library/MobileDevice/Provisioning Profiles/"
          mv -v TLS_Inspector.mobileprovision   "~/Library/MobileDevice/Provisioning Profiles/f2477cba-1359-4ec6-9ed6-cf8d0cbcc76f.mobileprovision"
          mv -v Inspect_Website.mobileprovision "~/Library/MobileDevice/Provisioning Profiles/d6c2be10-51a7-476c-9b37-7ca5e8d22874.mobileprovision"
          echo '-----BEGIN CERTIFICATE-----' > dev.crt
          echo '${{ secrets.APPLE_DEVELOPMENT_CERTIFICATE }}' >> dev.crt
          echo '-----END CERTIFICATE-----' >> dev.crt
          echo '${{ secrets.APPLE_DEVELOPMENT_PRIVATE_KEY }}' > dev.key.base64
          base64 -i dev.key.base64 -o dev.key --decode && rm dev.key.base64
          security import dev.crt -t cert -k ~/Library/Keychains/login.keychain-db -f pemseq -A
          echo 'imported dev.crt'
          security import dev.key -t priv -k ~/Library/Keychains/login.keychain-db -f openssl -A
          echo 'imported dev.key'
          rm dev.key dev.crt

      - name: "Prepare Build Environment"
        id: prepare
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "Switching to ${{ env.XCODE_VERSION }}"
          sudo xcode-select -s /Applications/${{ env.XCODE_VERSION }}.app/Contents/Developer
          xcode-select -p
          mkdir -p /Users/runner/derived_data
          echo "SWIFTLINT_CACHE_KEY=swiftlint_$(gh api repos/realm/swiftlint/releases/latest --jq '.assets[] | select(.name == "portable_swiftlint.zip") | .id')" >> "$GITHUB_OUTPUT"

      - name: "Restore Cached SwiftLint"
        id: restore_swiftlint
        uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 #pin v5.0.4
        with:
          key: ${{ steps.prepare.outputs.SWIFTLINT_CACHE_KEY }}
          path: |
            /Users/runner/bin/swiftlint

      - name: "Install SwiftLint"
        id: install_swiftlint
        if: ${{ steps.restore_swiftlint.outputs.cache-hit != 'true' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -p /Users/runner/bin
          SWIFTLINT_URL=$(gh api repos/realm/swiftlint/releases/latest --jq '.assets[] | select(.name == "portable_swiftlint.zip") | .browser_download_url')
          cd /Users/runner/bin
          curl -L -o swiftlint.zip "${SWIFTLINT_URL}"
          unzip swiftlint.zip
          rm swiftlint.zip LICENSE
          chmod a+x swiftlint

      - name: Build
        id: build
        run: |
          xcodebuild -resolvePackageDependencies -project "tls-inspector.xcodeproj"
          xcodebuild -scheme "Inspect Website" -project "tls-inspector.xcodeproj" -derivedDataPath ~/derived_data -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ env.TEST_DEVICE }}' build
          xcodebuild -scheme "TLS Inspector" -project "tls-inspector.xcodeproj" -derivedDataPath ~/derived_data -sdk iphonesimulator -destination 'platform=iOS Simulator,name=${{ env.TEST_DEVICE }}' build

      - name: "Install Go"
        id: install_go
        uses: actions/setup-go@4b73464bb391d4059bd26b0524d20df3927bd417 #pin v6.3.0
        with:
          go-version: "stable"
          cache-dependency-path: tlskit/Tests/TLSKitTests/TestServer/go.sum

      - name: Prepare Test Server
        id: testserver_prepare
        run: |
          cd tlskit/Tests/TLSKitTests/TestServer
          echo "Compiling test server"
          CGO_ENABLED=0 go build
          echo "Generating certifiate & key"
          ./TestServer -g
          xcrun simctl boot "${{ env.TEST_DEVICE }}"
          xcrun simctl keychain "${{ env.TEST_DEVICE }}" add-root-cert ./root.crt

      - name: Start Test Server
        id: testserver_start
        shell: bash
        run: |
          cd tlskit/Tests/TLSKitTests/TestServer
          nohup ./TestServer -c root.crt -k root.key &

      - name: Run Automated Tests
        id: certificatekit_tests
        run: |
          xcodebuild -scheme TLSKit test -derivedDataPath ~/derived_data -destination "platform=iOS Simulator,name=${{ env.TEST_DEVICE }}"

      - uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f #pin v7.0.0
        if: failure()
        with:
          name: test-results
          path: /Users/runner/derived_data/Logs/Test/Test-TLSKit-*.xcresult
