name: "Validate License"

on:
  push:
    paths:
      - '.github/workflows/validate_license.yml'
      - '**/*.swift'
      - '**/*.py'
      - '**/*.go'
  pull_request:
    paths:
      - '**/*.swift'
      - '**/*.py'
      - '**/*.go'

permissions:
  packages: read

jobs:
  build:
    name: "Validate License"
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd #pin v6.0.2
        with:
          persist-credentials: false

      - name: Validate license
        id: validate_license
        run: |
          python3 .github/check-license.py
