name: "Validate Localization"

on:
  push:
    paths:
      - '.github/workflows/validate_lang.yml'
      - 'tlsui/Sources/Localization/Strings/*.strings'
  pull_request:
    paths:
      - 'tlsui/Sources/Localization/Strings/*.strings'

permissions:
  packages: read

jobs:
  build:
    name: "Validate Localization"
    runs-on: ubuntu-slim
    steps:
      - name: Checkout Source
        id: checkout
        uses: actions/checkout@v6
      
      - name: Validate localization
        id: validate_localization
        run: |
          cd tlsui/Sources/Localization
          python3 lang.py
          if [[ $(git diff --stat) != '' ]]; then
            echo "::error ::Untracked changes to localization detected!"
            git status
            exit 1
          else
            echo "No untracked changes to localization detected"
          fi

      - name: Check Spelling
        id: spellcheck
        run: |
          cd .github/spellcheck
          npm ci
          node index.js ../../tlsui/Sources/Localization/Strings/en.strings
